server:
  port: 8001
mybatis:
  type-aliases-package: com.aiminhu.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-location: classpath:mybatis/mapper/*.xml
  mapUnderscoreToCamelCase: true

#spring的配置
spring:
  application:
    name: springcloud-provider-userinfo
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ********
